// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPITFG8RyN7xQFvE0NH1WZyiN3guvVCfQ',
    appId: '1:5704494639:web:1de9e376e8f09a808b60da',
    messagingSenderId: '5704494639',
    projectId: 'magiccity-6e868',
    authDomain: 'magiccity-6e868.firebaseapp.com',
    storageBucket: 'magiccity-6e868.firebasestorage.app',
    measurementId: 'G-GQ8SPT4EMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIv_vKTKsCq2llAjXEDIISXUzY5oST5Ng',
    appId: '1:5704494639:android:cd050af8b448963c8b60da',
    messagingSenderId: '5704494639',
    projectId: 'magiccity-6e868',
    storageBucket: 'magiccity-6e868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ05qTXcS5NMkjTA61ZL_MAYd75jOWJ-I',
    appId: '1:5704494639:ios:ed8f3cc34f32ee688b60da',
    messagingSenderId: '5704494639',
    projectId: 'magiccity-6e868',
    storageBucket: 'magiccity-6e868.firebasestorage.app',
    iosBundleId: 'com.example.firstAppFlutter',
  );
}
