platform :ios, '15.0'

# CocoaPods analytics disables
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
}

def flutter_install_ios_plugin_pods(flutter_application_path)
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')))
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
